
Array
(
    [id] => 10
    [name] => Susan Raymo
    [date_entered] => 2019-08-27 09:11:00
    [date_modified] => 2020-11-28 13:21:00
    [modified_user_id] => ernesto@coverageoneinsurance.com
    [created_by] => ernesto@coverageoneinsurance.com
    [description] => 
    [deleted] => 0
    [assigned_user_id] => 1
    [agerange] => 68
    [salutation] => Ms.
    [fullmailingaddress] => ,,,
    [fulladdress] => N7464 County Rd CC,Spring Valley,WI,54767
    [accountname] => 
    [returnedmailreason] => 
    [primarycounty] => 0
    [county] => 
    [medicaidid] => 
    [selfenrollpartdplan] => 
    [securityquestion] => 
    [nameonmedicarecard] => 
    [medicareidnumber] => 6X00f41JY18
    [dupsubscriberssn] => 
    [ipaddress] => 
    [accountholderssn] => 
    [accountholderlastname] => 
    [accountholderfirstname] => 
    [spouseoccupation] => 
    [primaryoccupation] => 
    [billingzippostalcode] => 
    [billingstateprovince] => 
    [billingcity] => 
    [mailingzippostalcode] => 
    [mailingcity] => 
    [mailingstreetaddress] => 
    [spousepreexisting] => 
    [spousessn] => 
    [spouselastname] => 
    [spousefirstname] => 
    [mothersmaidenname] => 
    [checknumber] => 
    [accountnumber] => 
    [routingnumbermustbe9digits] => 
    [branchzip] => 
    [branchstate] => 
    [branchcity] => 
    [branchstreetaddress] => 
    [bankname] => 
    [driverlicenseno] => 
    [driverlicensestate] => 
    [creditunion] => 
    [sfid] => 
    [expirationmonth] => 
    [creditcardnumber] => 
    [subscriberssn] => 390648384
    [primaryzippostalcode] => 54767
    [primarycity] => Spring Valley
    [primarystreetadress] => N7464 County Rd CC
    [primaryemail] => merty@svtel.net
    [primarylastname] => Raymo
    [alternateemail] => 
    [secondaryemail] => 
    [accountholderemail] => 
    [primaryfirstname] => Susan
    [physician3] => 
    [returnmailnotes] => 
    [prescriptionsnamedosagepharm] => 
    [agentnotes] => 
    [physiciannotes] => 
    [physician2] => 
    [primarycareproviderphoneanda] => 
    [oldsfnotes3] => 
    [oldsfnotes2] => 
    [notes] => 
    [oldsfnotes] => 
    [alternatephone] => 
    [accountholderphonenumber] => 
    [mobilephone] => 
    [leadconduitcallerid] => 
    [workphone] => 
    [phone] => (715) 778-5767
    [age] => 68
    [spouseweight] => 0
    [ccverificationcode] => 0
    [weight] => 280
    [agentvbcoffered] => 
    [frontedby] => 
    [originatingagent] => 
    [preferredcontactmethod] => 
    [besttimetocontact] => 
    [primarytobacconicotineuse] => 
    [accountholderrelationship] => 
    [mailingstateprovince] => 
    [spouseheight] => 
    [spousetobacconicotineuse] => 
    [spousegender] => 
    [accounttype] => 
    [expirationyear] => 
    [creditcardtype] => 
    [gender] => Female
    [paymenttype] => 
    [height] => 5ft 5in
    [primarystate] => WI
    [source] => LH
    [totalcommissions] => 0.00000000
    [medicarepartbeffectivedate] => 2019-10-01 00:00:00
    [returnedmaildate] => 
    [selfenrollpartdappointment] => 
    [selfenrollpartdcomplete] => 2019-09-16 00:00:00
    [medicarepartabenrollmentcomp] => 
    [medicarepartabenrollmentstar] => 
    [cancellifespan] => 
    [dobmd] => 
    [medicarepartaeffectivedate] => 
    [customerdate] => 
    [spousedob] => 
    [dob] => 1954-10-15
    [selfenrollpartdpremium] => 0.000000
    [currency_id] => 
    [medicaid] => 0
    [referral] => 0
    [checkrecoridngs] => 0
    [returnedmail] => 0
    [issunfire] => 0
    [fronted] => 0
    [dealafter545pm] => 0
    [updateonetimetemp] => 1
    [donotmail] => 0
    [donotemail] => 0
    [donotsms] => 0
    [smsoptin] => 0
    [lis] => 0
    [donotcall] => 0
    [unabletocheckmedicaidlis] => 0
    [adminlismedicaidcheck] => 0
    [confirmednoemail] => 0
    [emailoptin] => 0
    [mailingaddresssameasprimary] => 1
    [billingaddresssameasprimary] => 0
    [isthisafuturepay] => 0
    [billingstreetaddress] => 
)
