
Array
(
    [id] => 1
    [name] => Thomas Threatt
    [date_entered] => 2019-08-09 11:58:00
    [date_modified] => 2023-05-19 18:30:15
    [modified_user_id] => 1
    [created_by] => ernesto@coverageoneinsurance.com
    [description] => 
    [deleted] => 0
    [assigned_user_id] => 1
    [agentemail] => caitlin@coverageoneinsurance.com
    [agentlastname] => Mchale
    [plans] => G
    [serialnumber] => 
    [plannamecode] => 
    [plantype] => Medicare Supplement
    [dsstatustext] => 8/9/2019|Incomplete|Medicare Supplement|TransAmerica|//
    [medicaidnumber] => 
    [humanaapplicationcode] => 
    [oldamebeneficiary2] => 
    [oldamebeneficiary1] => 
    [lifetermlength] => 
    [appfilename] => Thomas Threatt_(205) 862-4341_
    [sobfilename] => Thomas Threatt_(205) 862-4341_
    [customerdatetext] => 8/7/2019
    [durationrange] => A. Less than 1 Day
    [canceldatetext] => //
    [effdatetext] => 9/1/2019
    [lun] => Like
    [plandurationrange] => A. Less than 1 Day
    [agerangeatdateofsale] => 0
    [agerange] => 2. 65-70
    [commtype] => 
    [customerdatepolicyquarter] => 0
    [cancelpolicyquarter] => 0
    [effectivepolicyquarter] => 3
    [agentfirstname] => Caitlin
    [humanafullname] => 
    [humanaemail] => 
    [amebenefit] => 
    [lissubsidyamount] => 
    [lunauditstatus] => 
    [carriercancellationcode] => 
    [humanaproductsplanname] => 
    [humanadateofbirth] => 
    [humanamedicareid] => 
    [humanapolicyid] => 
    [humanapartnerappid] => 
    [contingentbeneficiary] => 
    [primarybeneficiary] => 
    [carrierstatus1] => 
    [marxnewplan] => 
    [receipt] => 
    [callbacknotesforagent] => 
    [pcpid] => 
    [primarycaredoctorpcp] => 
    [hraconfnumber] => 
    [policynumber] => 016209447
    [enrollmentcode] => 
    [sfpersonalcode] => 
    [sepcode] => 
    [enrollmentperiod] => IEP
    [mimetype] => 
    [healthlifetimelimit] => 
    [statusauditnotes] => 
    [agentportalnotes] => 
    [beneficiarynotes] => 
    [applicationnotes] => 
    [agentdataentryissuenotes] => 
    [tonotes] => 
    [advocatecallnotes] => 
    [surveyoffered] => No
    [firstmaplan] => No
    [annotatednumber] => 
    [originateddid] => 
    [humanaphone] => 
    [qanumber] => (205) 862-4341
    [statuscontactauditresult] => 
    [advocatecallcompletedby] => 
    [csdateyear] => 2019
    [planduration] => 0
    [plandurationcalc] => 0
    [termduration] => 0
    [dayseffective] => 1353
    [ageatsale] => 23753
    [activeduration] => 0
    [declinelifespan] => 55
    [cancellifespan] => 0
    [relatedinsured] => 
    [humanaagentsan] => 0
    [humanaidcard] => 0
    [humanaenrollmentid] => 0
    [username] => cocaitlinmchale
    [carrier] => TransAmerica
    [status] => Cancelled
    [saveagent] => coAngelaMoya
    [rewritefrontrep] => AngelaMoya
    [verifiedby] => TestVerifier
    [salesto] => 
    [deductable] => undefined
    [colnsurance] => 100_0
    [appfee] => 0
    [hrastatus] => Done
    [checkboxtestfield] => no
    [inhouserewrite] => No
    [statusauditresult] => Accretion
    [rewritefrontedto] => COTESTTESTER
    [rewritefronter] => AngelaMoya
    [dataentryrep] => AngelaMoya
    [aepassignedagent] => Block
    [cshracompletedby] => 
    [humanastatus] => Done
    [humanaagentsfullname] => ALBERTOMORENOCALZADILLA
    [previouscarrier] => AARP
    [formularyexceptionneeded] => NA
    [cancelreason] => CMSTerminated
    [declinereason] => AnthemClosedPlanChangeComplete
    [salesrep] => 
    [isthisafuturepay] => No
    [a1monthlyadminfee] => undefined
    [timestod] => undefined
    [contingentbeneficiaryrelations] => Brother
    [primarybeneficiaryrelationship] => Daughter
    [vendor] => AM
    [aor] => AOR
    [fronterrep] => Ernesto
    [primarybeneficiaryperc] => 0.00000000
    [commission2020] => 0.00000000
    [commission2021] => 0.00000000
    [commission2022] => 0.00000000
    [commission2023] => 0.00000000
    [contingentbeneficiaryperc] => 0.00000000
    [commission] => 0.00000000
    [lifetimecommission] => 0.00000000
    [carriercommissions] => 0.00000000
    [annualizedpremium] => 1438.32000000
    [agentcallbackappt] => 
    [testver] => 
    [datesubmittedtoverification] => 2019-08-09 12:00:00
    [humanasignaturedate] => 
    [oepappointment] => 
    [futureenrollmentperiodcbnotes] => 
    [futureenrollmentperiodcallback] => 
    [day90aftereffectivefollowupcal] => 
    [day60aftereffectivefollowupcal] => 
    [day30aftereffectivefollowupcal] => 
    [initialwellnessvisitscheduled] => 
    [effectivedatecallcomplete] => 
    [carrierpolicypacketreceived] => 
    [dsnpsepfollowupappt] => 
    [welcomecallcomplete] => 2019-09-16 00:00:00
    [welcomeemailsent] => 
    [signeddate] => 2019-08-13 00:00:00
    [advocatecallbackscheduled] => 
    [cshracompleteddate] => 
    [manualvertimeentry] => 2019-08-09 12:00:00
    [sfdate] => 
    [savedate] => 
    [applicationsignaturedate] => 
    [dupstmtermdate1] => 
    [termdate] => 
    [statusauditdate2] => 
    [statusauditdate] => 
    [futurepaydeclinedate] => 
    [welcomeletterresent] => 
    [birthdaycardreturned] => 
    [welcomeletterreturned] => 
    [marxcheckdate] => 
    [canceldate] => 
    [declinedate] => 2019-10-01
    [issuedate] => 
    [customerdate] => 2019-08-07
    [movingdisenrollmentdate] => 
    [futurepaymentdate] => 
    [effectivedate] => 2019-09-01
    [onetimeapplicationfee] => 0.000000
    [currency_id] => 
    [maxoutofpocket] => 0.000000
    [lifecoverageamount] => 0.000000
    [cibenefit] => 0.000000
    [amecibenefit] => 0.000000
    [agentcommission] => 0.000000
    [premium] => 119.860000
    [chargebackcommission] => 0
    [missingincorrectmedications] => 0
    [advocatecallsentbacktoagent] => 0
    [rewrite] => 0
    [cscampaignassigned] => 0
    [agentrewrite] => 0
    [highrisk] => 0
    [applicationacceptedbycarrier] => 0
    [lumpsumheartattackandstrokerid] => 0
    [invasivecancerrecurrencerider] => 0
    [criticalconditionrider] => 0
    [exceptionneedednotmarked] => 0
    [sunfiretempmarker] => 0
    [marxlisactive] => 0.000000
    [marxlookupfailed] => 0
    [lunauditupdate] => 0
    [cpadeal] => 0
    [missinggender] => 0
    [narapp] => 0
    [narsob] => 0
    [dataverified] => 0
    [sunfire] => 1
    [nopreviousmedicareadvorpartdpl] => 0
    [partdendoflastplanyear] => 0
    [ismedicaid] => 0
    [pointagram] => 0
    [vertimeoverride] => 0
    [housedeal] => 0.000000
    [verrifiedreferral] => 0
    [paidhra] => 0
    [sfdnc] => 0
    [rewritebonus] => 0
    [unplacedrewrite] => 0
    [pastrd] => 0
    [isissued] => 0
    [ischurn] => 0
    [isplaced] => 0
    [nocommissionuploaded] => 0
    [chargedback] => 0
    [commissionpaid] => 0
    [q1count] => 0
    [isendofquarteractive] => 0
    [isnotissuedcxl] => 0
    [iscancel] => 0
    [isdecline] => 0
    [plantypecheck] => 1
    [advocatecallincomplete] => 0
    [flagfordatareview] => 0
    [isactive] => 0
    [carrierconfirmedmoving] => 0
    [sunfiredoctormismatch] => 0
    [advocatecallcomplete] => 0
    [removefromagentportal] => 0
    [itissuewithwelcomecall] => 0
    [welcomecallmade] => 0
    [partdinthisplanyear] => 0
    [reapp] => 0
    [payrolloverride] => 0
    [rewritepolicysubmitted] => 0
    [agentasigned] => 0
    [declinenotissuedconfirmed] => 0
    [missingsunfirecode] => 0
    [missingsecurityquestions] => 0
    [incorrectpersonalinfo] => 0
    [missingincorrectaddress] => 0
    [piorauthnotnotified] => 0
    [exceptionmarkerror] => 0
    [missingdoctor] => 0
    [payout] => 0.000000
)
